bot:
  inspection: update-grayskull
conda_build_tool: rattler-build
conda_forge_output_validation: true
conda_install_tool: pixi
github:
  branch_name: main
  tooling_branch_name: main
test: native_and_emulated
workflow_settings:
  free_disk_space: quick
provider:
  osx_arm64: default
